name: canteen_fbdb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets :
  - D:/flutter workspace/canteen_fbdb/lib/assets/featured.jpg
  - D:/flutter workspace/canteen_fbdb/lib/assets/sandwich.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/chinese.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/frankie.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/main_course.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/south_indian.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/snacks.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/breakfast.png
  - D:/flutter workspace/canteen_fbdb/lib/assets/user.png
